openapi: 3.0.3
info:
  title: Todo AI Chatbot API
  description: API for interacting with the AI chatbot that manages tasks
  version: 1.0.0
servers:
  - url: https://api.todo-ai-chatbot.com/v1
    description: Production server
  - url: https://staging.api.todo-ai-chatbot.com/v1
    description: Staging server
paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI assistant
      description: Allows a user to send a message to the AI assistant and receive a response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The message content from the user
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: string
                  format: uuid
                  description: Optional conversation ID to continue an existing conversation
                  example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '200':
          description: Successful response from the AI assistant
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                  - conversation_id
                properties:
                  response:
                    type: string
                    description: The AI assistant's response
                    example: "I've added the task 'buy groceries' to your list."
                  conversation_id:
                    type: string
                    format: uuid
                    description: The ID of the conversation
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  timestamp:
                    type: string
                    format: date-time
                    description: The timestamp of the response
                    example: "2023-10-05T14:48:00Z"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user doesn't have access to this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found - user or conversation doesn't exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_INPUT"
        message:
          type: string
          description: Human-readable error message
          example: "The request body is malformed"